### ISSUE TITLE
Add a check api for the connection test

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-logstore_standardqueued#10]
https://docs.moodle.org/dev/Check_API#Status_checks_.28status.29

**Comment by srdjan-catalyst** [comment]
Added check api b725916f46ae9ba03543b16ec4ba9cd6cb15aaf3

**Comment by brendanheywood** [comment]
This isn't working, see https://github.com/catalyst/moodle-logstore_standardqueued/issues/12

**Comment by dmitriim** [comment]
Check API shouldn't check if the plugin is disabled.

**Comment by dmitriim** [comment]
This one is done.
