### ISSUE TITLE
Only check is_operational when on the settings page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-logstore_standardqueued#12]
Otherwise it does this on all admin pages across the site and slows it all down

**Comment by srdjan-catalyst** [comment]
I have removed the check from settings.php and placed it in a check class b725916f46ae9ba03543b16ec4ba9cd6cb15aaf3. Do we need it on the settings page as well?

**Comment by brendanheywood** [comment]
@srdjan-catalyst can you please get into the habit of refering to the github issues in the commits and in pull requests so that github does all its usual magic:

https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls

**Comment by brendanheywood** [comment]
I don't think we need it on the settings page. A middle ground could just be a link to the status details page

btw the check isn't actually working:

http://moodle.local/report/status/index.php

You need to also tell moodle which report the check should go into, ie the 'status' report:

https://github.com/moodle/moodle/blob/master/admin/tool/task/lib.php#L32-L38

**Comment by brendanheywood** [comment]
The deep link when it works should be something like this:

/report/status/index.php?detail=tool_task_cronrunning

**Comment by dmitriim** [comment]
This one seems to be fixed.

**Comment by dmitriim** [comment]
Reopening this one as that is not properly done. Still needs to have is_operational check on the setting page.

**Comment by dmitriim** [comment]
Now it's finished
