### ISSUE TITLE
Broken nav bar when editing  a notice 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-logstore_standardqueued#24]
Should be:

Dashboard > Site administration > Site Notice > Manage Notice

Reality:

![image](https://user-images.githubusercontent.com/4626431/153313998-9b677e30-5478-41b9-998e-f80d3530ac4c.png)

**Comment by brendanheywood** [comment]
Wrong repo?

**Comment by dmitriim** [comment]
100%
