### ISSUE TITLE
Carefully measure the async timing and consider moving it to be asap rather than in shutdown handler

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-logstore_standardqueued#8]
so I've been poking around some profiles, from what I can see the queue makes an async curl call which takes about 130ms to complete. This is async but I believe it is waiting for it to finish before the request can be closed. So I think we are better off moving that to as soon as the event is triggered rather than waiting until the shutdown handler where it will be forced to sit and wait.

It would be good to test when there are multiple events triggered on the same page and double check they all run in parallel while the rest of the page keeps moving

**Comment by srdjan-catalyst** [comment]
This is possible to do as is. Set buffer size to 0 and it fires instantly. And it is faster.
