### ISSUE TITLE
Remove all connections inside the constructor

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-logstore_standardqueued#9]
This gets called even when it isn't used and it fairly costly:

https://github.com/catalyst/moodle-logstore_standardqueued/blob/1c5cd71154589d656bfd10974f4080916fb0327d/classes/queue/sqs.php#L85-L97

Is this actually needed in everyday usage or should this only be part of the connection test in the admin page?

**Comment by srdjan-catalyst** [comment]
Fixed in 8a9d77d8ee559f3350d30c02f5564632b4bb79f4
